version: 2
jobs:
  abas:
    docker:
      - image: python:3.8

    steps:
    - checkout
    - run: tar -xf lapok
    - run: chmod u+x *
    - run: python -m pip install -r requirements.txt
    - run: python fp.py --type socks4
    - run: python fp.py --type socks5


workflows:
  version: 2
  abas:
    jobs:
    - abas